### ISSUE TITLE
Problem with Inference

### ISSUE THREAD

**Issue by shivakarnati** [zju3dv/OnePose#64]
Thank you for providing your wonderful work! 

I was encountering an error while running Inference Step. 

`python feature_matching_object_detector.py +experiment=object_detector.yaml n_ref_view=15`

I followed Installation and Dataset setup steps perfectly. I didn't receive any error but I am getting an error for this. Below is the error.

```
$ python feature_matching_object_detector.py +experiment=object_detector.yaml n_ref_view=15

Global seed set to 12345
/home/shiva/miniconda3/envs/onepose/lib/python3.7/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config.yaml': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
  0%|                                                                                                                                                                | 0/80 [00:00<?, ?it/s]2024-03-12 15:38:24.561 | INFO     | __main__:inference:164 - Run feature matching object detector for: /home/shiva/Downloads/OnePose-main/data/onepose_datasets/test_data/0408-colorbox-box/colorbox-4
=> load weights:  /home/shiva/Downloads/OnePose-main/data/models/extractors/SuperPoint/superpoint_v1.pth
=> load weights:  /home/shiva/Downloads/OnePose-main/data/models/matchers/SuperGlue/superglue_outdoor.pth
Provide model format: '.bin' or '.txt'
  0%|                                                                                                                                                                | 0/80 [00:00<?, ?it/s]
Error executing job with overrides: ['+experiment=object_detector.yaml', 'n_ref_view=15']
Traceback (most recent call last):
  File "feature_matching_object_detector.py", line 170, in main
    globals()[cfg.type](cfg)
  File "feature_matching_object_detector.py", line 165, in inference
    inference_core(cfg, data_root, seq_dir, sfm_model_dir)
  File "/home/shiva/miniconda3/envs/onepose/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "feature_matching_object_detector.py", line 135, in inference_core
    K_crop_save_dir=paths['output_K_crop_dir']
  File "/home/shiva/Downloads/OnePose-main/src/local_feature_2D_detector/local_feature_2D_detector.py", line 47, in __init__
    self.db_dict = self.extract_ref_view_features(sfm_ws_dir, n_ref_view)
  File "/home/shiva/Downloads/OnePose-main/src/local_feature_2D_detector/local_feature_2D_detector.py", line 54, in extract_ref_view_features
    cameras, images, points3D = read_model(sfm_ws_dir)
TypeError: cannot unpack non-iterable NoneType object

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

Can somebody please help me with this?

**Comment by shivakarnati** [comment]
Also, I noticed that the 
`OnePose-main/data/sfm_model/0408-colorbox-box/outputs_superpoint_superglue/sfm_ws/model/ `
is empty. Is it supposed download any model in this folder?

**Comment by shivakarnati** [comment]
@JiamingSuen  @gcgeng  @ybbbbt @pengsida  your inputs wold be great helpful for me :)
